### ISSUE TITLE
Is there a way to run this?

### ISSUE THREAD

**Issue by dylanmc** [shickey/HMMM.js#1]
The web version on github.io is amazing! I've tried to stand up HTML and javascript infrastructure around the files in the repo, but I couldn't get it working. Is this as intended, or can you provide help getting it running offline?

**Comment by shickey** [comment]
Glad you like the online version! If you like, you can switch to the [`gh-pages`](https://github.com/shickey/HMMM.js/tree/gh-pages) branch which contains all the code for the github.io site. You _should_ be able to clone that branch and run it locally with minimal hassle on any local web server. It contains the HMMM.js code run through [browserify](http://browserify.org/) along with all the frontend frameworks and libraries for the site (angular, ace editor, bootstrap, etc.). If you'd like to get the HMMM.js code running in a different way, let me know what errors you're running into and I can try to point you in the right direction.

**Comment by dylanmc** [comment]
Perfect! 

With this branch checked out, I was able to run everything perfectly on my local machine:

```
% cd HMMM.js
% python -m SimpleHTTPServer
```

and then pointing my browser to `http://127.0.0.1:8000`

Thanks very much.

**Comment by shickey** [comment]
Glad to hear it! Feel free to pass along any feedback/ideas as you dive into the code.
